version: "3"

services:
  portainer:
    container_name: "Portainer"
    image: "portainer/portainer-ce"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./data:/data"
    ports:
      - "8000:8000"
      - "9000:9000"
    restart: always
